export type Salt = {
  salt: string;
  synonyms: string[];
  strength: string;
  amountPerUnitMg?: number;
  smiles: string;
  inchikey: string;
};

export type Brand = {
  id: string;
  brandName: string;
  aliases: string[];
  manufacturer: string;
  category: string;
  salts: Salt[];
  sourceType: "India-market curated dataset" | "Tata 1mg India-market reference";
  sourceUrls?: string[];
  region?: "Karnataka" | "Telangana" | "Tamil Nadu" | "Kerala" | "Andhra Pradesh";
};

export const brands: Brand[] = [
  { id: "dolo-650", brandName: "Dolo 650", aliases: ["dolo", "dolo650", "paracetamol 650"], manufacturer: "Micro Labs", category: "Analgesic / antipyretic", sourceType: "Tata 1mg India-market reference", sourceUrls: ["https://www.1mg.com/drugs/dolo-650-tablet-74467"], salts: [{ salt: "Paracetamol", synonyms: ["Acetaminophen"], strength: "650 mg", amountPerUnitMg: 650, smiles: "CC(=O)NC1=CC=C(O)C=C1", inchikey: "RZVAJINKPMORJF-UHFFFAOYSA-N" }] },
  { id: "combiflam", brandName: "Combiflam", aliases: ["combiflam tablet", "ibuprofen paracetamol"], manufacturer: "Sanofi Consumer Healthcare India Limited", category: "NSAID / analgesic", sourceType: "Tata 1mg India-market reference", sourceUrls: ["https://www.1mg.com/drugs/combiflam-tablet-325414"], salts: [{ salt: "Ibuprofen", synonyms: ["Ibuprofenum"], strength: "400 mg", amountPerUnitMg: 400, smiles: "CC(C)CC1=CC=C(C=C1)C(C)C(=O)O", inchikey: "HEFNNWSXXWATRW-UHFFFAOYSA-N" }, { salt: "Paracetamol", synonyms: ["Acetaminophen"], strength: "325 mg", amountPerUnitMg: 325, smiles: "CC(=O)NC1=CC=C(O)C=C1", inchikey: "RZVAJINKPMORJF-UHFFFAOYSA-N" }] },
  { id: "clavam-625", brandName: "Clavam 625", aliases: ["clavam", "clavam625", "amoxycillin clavulanic acid"], manufacturer: "Alkem Laboratories Ltd", category: "Antibiotic / fixed-dose combination", sourceType: "Tata 1mg India-market reference", sourceUrls: ["https://www.1mg.com/drugs/clavam-625-tablet-63841"], salts: [{ salt: "Amoxicillin", synonyms: ["Amoxycillin"], strength: "500 mg", amountPerUnitMg: 500, smiles: "CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=C(C=C3)O)N)C(=O)O)C", inchikey: "LSQZJLSUYDQPKJ-MBNYWOFBSA-N" }, { salt: "Clavulanic Acid", synonyms: ["Clavulanate"], strength: "125 mg", amountPerUnitMg: 125, smiles: "C1C2N(C1=O)C(C(O2)=CCO)C(=O)O", inchikey: "HNYUZQJHSCJIDK-UHFFFAOYSA-N" }] },
  { id: "moxikind-cv-625", brandName: "Moxikind-CV 625", aliases: ["moxikind cv", "moxikind-cv", "moxikind cv 625"], manufacturer: "Mankind Pharma Ltd", category: "Antibiotic / fixed-dose combination", sourceType: "Tata 1mg India-market reference", sourceUrls: ["https://www.1mg.com/drugs/moxikind-cv-625-tablet-329310"], salts: [{ salt: "Amoxicillin", synonyms: ["Amoxycillin"], strength: "500 mg", amountPerUnitMg: 500, smiles: "CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=C(C=C3)O)N)C(=O)O)C", inchikey: "LSQZJLSUYDQPKJ-MBNYWOFBSA-N" }, { salt: "Clavulanic Acid", synonyms: ["Clavulanate"], strength: "125 mg", amountPerUnitMg: 125, smiles: "C1C2N(C1=O)C(C(O2)=CCO)C(=O)O", inchikey: "HNYUZQJHSCJIDK-UHFFFAOYSA-N" }] },
  { id: "augmentin-625", brandName: "Augmentin 625 Duo", aliases: ["augmentin", "augmentin625", "augmentin 625", "amoxicillin clavulanate"], manufacturer: "GSK", category: "Antibiotic", sourceType: "India-market curated dataset", sourceUrls: ["https://store.arka.health/product/augmentin-625-duo-tablets-a-stripe-of-10-tablets/"], salts: [{ salt: "Amoxicillin", synonyms: ["Amoxycillin"], strength: "500 mg", amountPerUnitMg: 500, smiles: "CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=C(C=C3)O)N)C(=O)O)C", inchikey: "LSQZJLSUYDQPKJ-MBNYWOFBSA-N" }, { salt: "Clavulanic Acid", synonyms: ["Clavulanate"], strength: "125 mg", amountPerUnitMg: 125, smiles: "C1C2N(C1=O)C(C(O2)=CCO)C(=O)O", inchikey: "HNYUZQJHSCJIDK-UHFFFAOYSA-N" }] },
  { id: "benadryl", brandName: "Benadryl Syrup", aliases: ["benadryl", "benadryl syrup", "benadryl cough syrup", "diphenhydramine syrup"], manufacturer: "JNTL Consumer Health (India) Pvt. Ltd.", category: "Antihistamine / cough syrup", sourceType: "Tata 1mg India-market reference", sourceUrls: ["https://www.1mg.com/drugs/benadryl-syrup-114690"], salts: [{ salt: "Diphenhydramine", synonyms: ["Diphenhydramine HCl"], strength: "14.08 mg / 5 mL", amountPerUnitMg: 14.08, smiles: "CN(C)CCOC(C1=CC=CC=C1)C2=CC=CC=C2", inchikey: "ZZVUWRFHKOJYQO-UHFFFAOYSA-N" }, { salt: "Ammonium Chloride", synonyms: ["Ammonium chloride"], strength: "138 mg / 5 mL", amountPerUnitMg: 138, smiles: "[NH4+].[Cl-]", inchikey: "NLXLAEXVIDQMFP-UHFFFAOYSA-N" }, { salt: "Sodium Citrate", synonyms: ["Trisodium citrate"], strength: "57.03 mg / 5 mL", amountPerUnitMg: 57.03, smiles: "C(C(=O)[O-])C(CC(=O)[O-])(C(=O)[O-])O.[Na+].[Na+].[Na+]", inchikey: "HRXKRNGNAMMEHJ-UHFFFAOYSA-K" }] },
  { id: "warf-5", brandName: "Warf 5", aliases: ["warf", "warfarin 5", "warfarin"], manufacturer: "Cipla Ltd", category: "Anticoagulant", sourceType: "Tata 1mg India-market reference", sourceUrls: ["https://www.1mg.com/drugs/warf-5-tablet-541663"], salts: [{ salt: "Warfarin", synonyms: ["Warfarin sodium"], strength: "5 mg", amountPerUnitMg: 5, smiles: "CC(=O)CC(C1=CC=CC=C1)C2=C(C3=CC=CC=C3OC2=O)O", inchikey: "PJVWKTKQXJZVAA-UHFFFAOYSA-N" }] },
  { id: "tamoxifen", brandName: "Tamoxifen Citrate 20mg Tablet", aliases: ["tamoxifen", "tamoxifen 20", "tamoxifen citrate"], manufacturer: "Jan Aushadhi", category: "Oncology / SERM", sourceType: "Tata 1mg India-market reference", sourceUrls: ["https://www.1mg.com/drugs/tamoxifen-citrate-20mg-tablet-813615"], salts: [{ salt: "Tamoxifen", synonyms: ["Tamoxifen citrate"], strength: "20 mg", amountPerUnitMg: 20, smiles: "CCC(=C(C1=CC=CC=C1)C2=CC=C(C=C2)OCCN(C)C)C3=CC=CC=C3", inchikey: "NKANXQFJJICGDU-UHFFFAOYSA-N" }] },
  { id: "methotrexate", brandName: "MTX 5mg Tablet", aliases: ["methotrexate", "mtx 5", "mtx 5mg"], manufacturer: "Nexgen Rx Life Science Pvt Ltd", category: "Oncology / immunosuppressant", sourceType: "Tata 1mg India-market reference", sourceUrls: ["https://www.1mg.com/drugs/mtx-5mg-tablet-400030"], salts: [{ salt: "Methotrexate", synonyms: ["MTX"], strength: "5 mg", amountPerUnitMg: 5, smiles: "CN(CC1=CN=C2C(=N1)C(=NC(=N2)N)N)C3=CC=C(C=C3)C(=O)NC(CCC(=O)O)C(=O)O", inchikey: "FBOZXEJYQVNJAA-UHFFFAOYSA-N" }] },
  { id: "pantoprazole", brandName: "Pantocid Tablet", aliases: ["pantoprazole", "pantop", "pantocid"], manufacturer: "Sun Pharmaceutical Industries Ltd", category: "Proton-pump inhibitor", sourceType: "Tata 1mg India-market reference", sourceUrls: ["https://www.1mg.com/drugs/pantocid-tablet-332527"], salts: [{ salt: "Pantoprazole", synonyms: ["Pantoprazole sodium"], strength: "40 mg", amountPerUnitMg: 40, smiles: "COC1=NC=NC2=C1C(=NN2)S(=O)CC3=CC=C(C=C3)OC", inchikey: "IQPSEEYGBUAQFF-UHFFFAOYSA-N" }] },
  { id: "azithral", brandName: "Azithral 500", aliases: ["azithral", "azithromycin"], manufacturer: "Alembic", category: "Macrolide antibiotic", sourceType: "India-market curated dataset", sourceUrls: ["https://pharmeasy.in/online-medicine-order/azithral-500mg-tab-5-s-183974"], salts: [{ salt: "Azithromycin", synonyms: ["Azithromycin dihydrate"], strength: "500 mg", amountPerUnitMg: 500, smiles: "CCC1C(C(C(C(C(O1)C)N(C)C)O)C)OC2C(C(C(C(O2)C)O)OC)N(C)C", inchikey: "MQTOSJVFKKJCRP-UHFFFAOYSA-N" }]   },
  { id: "crocin-advance", brandName: "Crocin Advance 500", aliases: ["crocin", "crocin advance", "paracetamol 500"], manufacturer: "GlaxoSmithKline Consumer Healthcare", category: "Analgesic / antipyretic", sourceType: "India-market curated dataset", sourceUrls: ["https://www.1mg.com/drugs/crocin-advance-500mg-tablet-11952"], salts: [{ salt: "Paracetamol", synonyms: ["Acetaminophen"], strength: "500 mg", amountPerUnitMg: 500, smiles: "CC(=O)NC1=CC=C(O)C=C1", inchikey: "RZVAJINKPMORJF-UHFFFAOYSA-N" }] },
  { id: "calpol-500", brandName: "Calpol 500", aliases: ["calpol", "calpol 500", "paracetamol tablet"], manufacturer: "GlaxoSmithKline Consumer Healthcare", category: "Analgesic / antipyretic", sourceType: "India-market curated dataset", sourceUrls: ["https://www.1mg.com/drugs/calpol-500mg-tablet-11302"], salts: [{ salt: "Paracetamol", synonyms: ["Acetaminophen"], strength: "500 mg", amountPerUnitMg: 500, smiles: "CC(=O)NC1=CC=C(O)C=C1", inchikey: "RZVAJINKPMORJF-UHFFFAOYSA-N" }] },
  { id: "ecosprin-75", brandName: "Ecosprin 75", aliases: ["ecosprin", "ecosprin 75", "aspirin 75"], manufacturer: "USV Pvt Ltd", category: "Antiplatelet", sourceType: "India-market curated dataset", sourceUrls: ["https://www.apollopharmacy.in/medicine/ecosprin-75mg-tablet"], salts: [{ salt: "Aspirin", synonyms: ["Acetylsalicylic acid"], strength: "75 mg", amountPerUnitMg: 75, smiles: "CC(=O)OC1=CC=CC=C1C(=O)O", inchikey: "BSYNRYMUTXBXSQ-UHFFFAOYSA-N" }] },
  { id: "pantocid-40", brandName: "Pantocid 40", aliases: ["pantocid", "pantoprazole 40"], manufacturer: "Sun Pharma Laboratories", category: "Proton-pump inhibitor", sourceType: "India-market curated dataset", sourceUrls: ["https://pharmeasy.in/online-medicine-order/pantocid-40mg-strip-of-15-tablets-25758"], salts: [{ salt: "Pantoprazole", synonyms: ["Pantoprazole sodium"], strength: "40 mg", amountPerUnitMg: 40, smiles: "COC1=NC=NC2=C1C(=NN2)S(=O)CC3=CC=C(C=C3)OC", inchikey: "IQPSEEYGBUAQFF-UHFFFAOYSA-N" }] },
  { id: "brufen-400", brandName: "Brufen 400", aliases: ["brufen", "brufen 400", "ibuprofen 400"], manufacturer: "Abbott India Ltd", category: "NSAID / analgesic", sourceType: "India-market curated dataset", sourceUrls: ["https://pharmeasy.in/online-medicine-order/brufen-400mg-tablet-38362"], salts: [{ salt: "Ibuprofen", synonyms: ["Ibuprofenum"], strength: "400 mg", amountPerUnitMg: 400, smiles: "CC(C)CC1=CC=C(C=C1)C(C)C(=O)O", inchikey: "HEFNNWSXXWATRW-UHFFFAOYSA-N" }] },
  { id: "amoxyclav-625", brandName: "Amoxyclav 625", aliases: ["amoxyclav", "amoxyclav625", "amoxicillin clavulanate"], manufacturer: "Abbott Healthcare Pvt Ltd", category: "Antibiotic / fixed-dose combination", sourceType: "India-market curated dataset", sourceUrls: ["https://pharmeasy.in/online-medicine-order/amoxyclav-625mg-tab-10-s-214164"], salts: [{ salt: "Amoxicillin", synonyms: ["Amoxycillin"], strength: "500 mg", amountPerUnitMg: 500, smiles: "CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=C(C=C3)O)N)C(=O)O)C", inchikey: "LSQZJLSUYDQPKJ-MBNYWOFBSA-N" }, { salt: "Clavulanic Acid", synonyms: ["Clavulanate"], strength: "125 mg", amountPerUnitMg: 125, smiles: "C1C2N(C1=O)C(C(O2)=CCO)C(=O)O", inchikey: "HNYUZQJHSCJIDK-UHFFFAOYSA-N" }] },
  { id: "azee-500", brandName: "Azee 500", aliases: ["azee", "azee 500", "azithromycin 500"], manufacturer: "Cipla Ltd", category: "Macrolide antibiotic", sourceType: "India-market curated dataset", sourceUrls: ["https://www.apollopharmacy.in/medicine/azee-500mg-tablet"], salts: [{ salt: "Azithromycin", synonyms: ["Azithromycin dihydrate"], strength: "500 mg", amountPerUnitMg: 500, smiles: "CCC1C(C(C(C(C(O1)C)N(C)C)O)C)OC2C(C(C(C(O2)C)O)OC)N(C)C", inchikey: "MQTOSJVFKKJCRP-UHFFFAOYSA-N" }] },
  { id: "allercet-l", brandName: "Allercet-L", aliases: ["allercet l", "allercet-l", "levocetirizine 5", "levocetirizine"], manufacturer: "Micro Labs Ltd", category: "Antihistamine", region: "Karnataka", sourceType: "India-market curated dataset", sourceUrls: ["https://www.1mg.com/drugs/allercet-l-tablet-15414"], salts: [{ salt: "Levocetirizine", synonyms: ["Levocetirizine dihydrochloride"], strength: "5 mg", amountPerUnitMg: 5, smiles: "C1CN(CCN1CCOCC(=O)O)C(C2=CC=CC=C2)C3=CC=C(C=C3)Cl.Cl.Cl", inchikey: "PGLIUCLTXOYQMV-GHVWMZMZSA-N" }] },
  { id: "omez-20", brandName: "Omez 20", aliases: ["omez", "omez 20", "omeprazole 20"], manufacturer: "Dr Reddy's Laboratories Ltd", category: "Proton-pump inhibitor", region: "Telangana", sourceType: "India-market curated dataset", sourceUrls: ["https://pharmeasy.in/online-medicine-order/omez-20-cap-20-s-173904"], salts: [{ salt: "Omeprazole", synonyms: ["Omeprazole magnesium"], strength: "20 mg", amountPerUnitMg: 20, smiles: "CC1=CN=C(C(=C1OC)C)CS(=O)C2=NC3=C(N2)C=C(C=C3)OC", inchikey: "SUBDBMMJDZJVOS-UHFFFAOYSA-N" }] },
  { id: "toprazol-d", brandName: "Toprazol-D", aliases: ["toprazol d", "toprazol-d", "pantoprazole domperidone"], manufacturer: "Karnataka Antibiotics & Pharmaceuticals Ltd", category: "Proton-pump inhibitor / prokinetic fixed-dose combination", region: "Karnataka", sourceType: "India-market curated dataset", sourceUrls: ["https://www.kaplindia.com/toprazol-d/"], salts: [{ salt: "Pantoprazole", synonyms: ["Pantoprazole sodium"], strength: "40 mg", amountPerUnitMg: 40, smiles: "COC1=NC=NC2=C1C(=NN2)S(=O)CC3=CC=C(C=C3)OC", inchikey: "IQPSEEYGBUAQFF-UHFFFAOYSA-N" }, { salt: "Domperidone", synonyms: ["Domperidone maleate"], strength: "30 mg", amountPerUnitMg: 30, smiles: "C1CN(CCC1N2C3=C(C=C(C=C3)Cl)NC2=O)CCCN4C5=CC=CC=C5NC4=O", inchikey: "FGXWKSZFVQUSTL-UHFFFAOYSA-N" }] },
  { id: "medomol-500", brandName: "Medomol 500", aliases: ["medomol", "medomol 500", "medopharm paracetamol"], manufacturer: "Medopharm Pvt Ltd", category: "Analgesic / antipyretic", region: "Tamil Nadu", sourceType: "India-market curated dataset", sourceUrls: ["https://www.medopharm.com/radiant/medomol-paracetamol-500mg-tablets/"], salts: [{ salt: "Paracetamol", synonyms: ["Acetaminophen"], strength: "500 mg", amountPerUnitMg: 500, smiles: "CC(=O)NC1=CC=C(O)C=C1", inchikey: "RZVAJINKPMORJF-UHFFFAOYSA-N" }] },
  { id: "keramycin-ksdp-500", brandName: "Keramycin (KSDP) 500", aliases: ["keramycin ksdp", "keramycin azithromycin", "keramycin azithromycin 500", "ksdp keramycin"], manufacturer: "Kerala State Drugs & Pharmaceuticals Ltd", category: "Macrolide antibiotic", region: "Kerala", sourceType: "India-market curated dataset", sourceUrls: ["https://kerala.gov.in/articledetail/OTE4MjY4NTE5LjUy/0", "https://ksdp.co.in/portfolio/tablets/"], salts: [{ salt: "Azithromycin", synonyms: ["Azithromycin dihydrate"], strength: "500 mg (KSDP catalog cross-reference)", amountPerUnitMg: 500, smiles: "CCC1C(C(C(C(C(O1)C)N(C)C)O)C)OC2C(C(C(C(O2)C)O)OC)N(C)C", inchikey: "MQTOSJVFKKJCRP-UHFFFAOYSA-N" }] },
  { id: "keramycin-250", brandName: "Keramycin 250", aliases: ["keramycin", "keramycin 250", "keramycin capsule", "chloramphenicol 250"], manufacturer: "Macwell Pharmaceuticals", category: "Antibiotic", sourceType: "India-market curated dataset", sourceUrls: ["https://www.1mg.com/drugs/keramycin-250mg-capsule-583743"], salts: [{ salt: "Chloramphenicol", synonyms: ["Chloramphenicol base"], strength: "250 mg", amountPerUnitMg: 250, smiles: "C1=CC(=CC=C1C(C(CO)NC(=O)C(Cl)Cl)O)[N+](=O)[O-]", inchikey: "WIIZWVCIJKGZOK-RKDXNWHRSA-N" }] },
];

export const uniqueSaltCount = new Set(brands.flatMap((brand) => brand.salts.map((salt) => salt.salt))).size;

export function normalizeBrandQuery(query: string) {
  const normalized = query.trim().toLowerCase().replace(/[^a-z0-9]/g, "");
  return brands.filter((brand) => [brand.brandName, ...brand.aliases].some((value) => value.toLowerCase().replace(/[^a-z0-9]/g, "").includes(normalized)));
}

export function getBrandsByIds(ids: string[]) {
  return brands.filter((brand) => ids.includes(brand.id));
}
