export type Salt = {
  salt: string;
  synonyms: string[];
  strength: string;
  amountPerUnitMg?: number;
  smiles: string;
  inchikey: string;
};

export type Brand = {
  id: string;
  brandName: string;
  aliases: string[];
  manufacturer: string;
  category: string;
  salts: Salt[];
  sourceType: "Local curated prototype dataset";
  sourceUrls?: string[];
  region?: "Karnataka" | "Telangana" | "Tamil Nadu" | "Kerala" | "Andhra Pradesh";
};

export const brands: Brand[] = [
  { id: "dolo-650", brandName: "Dolo 650", aliases: ["dolo", "dolo650", "paracetamol 650"], manufacturer: "Micro Labs", category: "Analgesic / antipyretic", sourceType: "Local curated prototype dataset", salts: [{ salt: "Paracetamol", synonyms: ["Acetaminophen"], strength: "650 mg", amountPerUnitMg: 650, smiles: "CC(=O)NC1=CC=C(O)C=C1", inchikey: "RZVAJINKPMORJF-UHFFFAOYSA-N" }] },
  { id: "combiflam", brandName: "Combiflam", aliases: ["combiflam tablet", "ibuprofen paracetamol"], manufacturer: "Sanofi India", category: "NSAID / analgesic", sourceType: "Local curated prototype dataset", salts: [{ salt: "Ibuprofen", synonyms: ["Ibuprofenum"], strength: "400 mg", amountPerUnitMg: 400, smiles: "CC(C)CC1=CC=C(C=C1)C(C)C(=O)O", inchikey: "HEFNNWSXXWATRW-UHFFFAOYSA-N" }, { salt: "Paracetamol", synonyms: ["Acetaminophen"], strength: "325 mg", amountPerUnitMg: 325, smiles: "CC(=O)NC1=CC=C(O)C=C1", inchikey: "RZVAJINKPMORJF-UHFFFAOYSA-N" }] },
  { id: "augmentin-625", brandName: "Augmentin 625", aliases: ["augmentin", "augmentin625", "amoxicillin clavulanate"], manufacturer: "GSK", category: "Antibiotic", sourceType: "Local curated prototype dataset", salts: [{ salt: "Amoxicillin", synonyms: ["Amoxycillin"], strength: "500 mg", amountPerUnitMg: 500, smiles: "CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=C(C=C3)O)N)C(=O)O)C", inchikey: "LSQZJLSUYDQPKJ-MBNYWOFBSA-N" }, { salt: "Clavulanic Acid", synonyms: ["Clavulanate"], strength: "125 mg", amountPerUnitMg: 125, smiles: "C1C2N(C1=O)C(C(O2)=CCO)C(=O)O", inchikey: "HNYUZQJHSCJIDK-UHFFFAOYSA-N" }] },
  { id: "benadryl", brandName: "Benadryl Cough Syrup", aliases: ["benadryl", "diphenhydramine syrup"], manufacturer: "Kenvue", category: "Antihistamine / cold", sourceType: "Local curated prototype dataset", salts: [{ salt: "Diphenhydramine", synonyms: ["Diphenhydramine HCl"], strength: "14 mg / 5 mL", amountPerUnitMg: 14, smiles: "CN(C)CCOC(C1=CC=CC=C1)C2=CC=CC=C2", inchikey: "ZZVUWRFHKOJYQO-UHFFFAOYSA-N" }] },
  { id: "warf-5", brandName: "Warf 5", aliases: ["warf", "warfarin 5", "warfarin"], manufacturer: "Cipla", category: "Anticoagulant", sourceType: "Local curated prototype dataset", salts: [{ salt: "Warfarin", synonyms: ["Warfarin sodium"], strength: "5 mg", amountPerUnitMg: 5, smiles: "CC(=O)CC(C1=CC=CC=C1)C2=C(C3=CC=CC=C3OC2=O)O", inchikey: "PJVWKTKQXJZVAA-UHFFFAOYSA-N" }] },
  { id: "tamoxifen", brandName: "Tamoxifen 20 mg", aliases: ["tamoxifen", "tamoxifen 20"], manufacturer: "Cipla", category: "Oncology / SERM", sourceType: "Local curated prototype dataset", salts: [{ salt: "Tamoxifen", synonyms: ["Tamoxifen citrate"], strength: "20 mg", amountPerUnitMg: 20, smiles: "CCC(=C(C1=CC=CC=C1)C2=CC=C(C=C2)OCCN(C)C)C3=CC=CC=C3", inchikey: "NKANXQFJJICGDU-UHFFFAOYSA-N" }] },
  { id: "methotrexate", brandName: "Methotrexate 5 mg", aliases: ["methotrexate", "mtx 5"], manufacturer: "Cipla", category: "Oncology / immunosuppressant", sourceType: "Local curated prototype dataset", salts: [{ salt: "Methotrexate", synonyms: ["MTX"], strength: "5 mg", amountPerUnitMg: 5, smiles: "CN(CC1=CN=C2C(=N1)C(=NC(=N2)N)N)C3=CC=C(C=C3)C(=O)NC(CCC(=O)O)C(=O)O", inchikey: "FBOZXEJYQVNJAA-UHFFFAOYSA-N" }] },
  { id: "pantoprazole", brandName: "Pantoprazole 40", aliases: ["pantoprazole", "pantop"], manufacturer: "Sun Pharma", category: "Proton-pump inhibitor", sourceType: "Local curated prototype dataset", salts: [{ salt: "Pantoprazole", synonyms: ["Pantoprazole sodium"], strength: "40 mg", amountPerUnitMg: 40, smiles: "COC1=NC=NC2=C1C(=NN2)S(=O)CC3=CC=C(C=C3)OC", inchikey: "IQPSEEYGBUAQFF-UHFFFAOYSA-N" }] },
  { id: "azithral", brandName: "Azithral 500", aliases: ["azithral", "azithromycin"], manufacturer: "Alembic", category: "Macrolide antibiotic", sourceType: "Local curated prototype dataset", salts: [{ salt: "Azithromycin", synonyms: ["Azithromycin dihydrate"], strength: "500 mg", amountPerUnitMg: 500, smiles: "CCC1C(C(C(C(C(O1)C)N(C)C)O)C)OC2C(C(C(C(O2)C)O)OC)N(C)C", inchikey: "MQTOSJVFKKJCRP-UHFFFAOYSA-N" }]   },
  { id: "crocin-advance", brandName: "Crocin Advance 500", aliases: ["crocin", "crocin advance", "paracetamol 500"], manufacturer: "GlaxoSmithKline Consumer Healthcare", category: "Analgesic / antipyretic", sourceType: "Local curated prototype dataset", sourceUrls: ["https://www.1mg.com/drugs/crocin-advance-500mg-tablet-11952"], salts: [{ salt: "Paracetamol", synonyms: ["Acetaminophen"], strength: "500 mg", amountPerUnitMg: 500, smiles: "CC(=O)NC1=CC=C(O)C=C1", inchikey: "RZVAJINKPMORJF-UHFFFAOYSA-N" }] },
  { id: "calpol-500", brandName: "Calpol 500", aliases: ["calpol", "calpol 500", "paracetamol tablet"], manufacturer: "GlaxoSmithKline Consumer Healthcare", category: "Analgesic / antipyretic", sourceType: "Local curated prototype dataset", sourceUrls: ["https://www.1mg.com/drugs/calpol-500mg-tablet-11302"], salts: [{ salt: "Paracetamol", synonyms: ["Acetaminophen"], strength: "500 mg", amountPerUnitMg: 500, smiles: "CC(=O)NC1=CC=C(O)C=C1", inchikey: "RZVAJINKPMORJF-UHFFFAOYSA-N" }] },
  { id: "ecosprin-75", brandName: "Ecosprin 75", aliases: ["ecosprin", "ecosprin 75", "aspirin 75"], manufacturer: "USV Pvt Ltd", category: "Antiplatelet", sourceType: "Local curated prototype dataset", sourceUrls: ["https://www.apollopharmacy.in/medicine/ecosprin-75mg-tablet"], salts: [{ salt: "Aspirin", synonyms: ["Acetylsalicylic acid"], strength: "75 mg", amountPerUnitMg: 75, smiles: "CC(=O)OC1=CC=CC=C1C(=O)O", inchikey: "BSYNRYMUTXBXSQ-UHFFFAOYSA-N" }] },
  { id: "pantocid-40", brandName: "Pantocid 40", aliases: ["pantocid", "pantoprazole 40"], manufacturer: "Sun Pharma Laboratories", category: "Proton-pump inhibitor", sourceType: "Local curated prototype dataset", sourceUrls: ["https://pharmeasy.in/online-medicine-order/pantocid-40mg-strip-of-15-tablets-25758"], salts: [{ salt: "Pantoprazole", synonyms: ["Pantoprazole sodium"], strength: "40 mg", amountPerUnitMg: 40, smiles: "COC1=NC=NC2=C1C(=NN2)S(=O)CC3=CC=C(C=C3)OC", inchikey: "IQPSEEYGBUAQFF-UHFFFAOYSA-N" }] },
  { id: "brufen-400", brandName: "Brufen 400", aliases: ["brufen", "brufen 400", "ibuprofen 400"], manufacturer: "Abbott India Ltd", category: "NSAID / analgesic", sourceType: "Local curated prototype dataset", sourceUrls: ["https://pharmeasy.in/online-medicine-order/brufen-400mg-tablet-38362"], salts: [{ salt: "Ibuprofen", synonyms: ["Ibuprofenum"], strength: "400 mg", amountPerUnitMg: 400, smiles: "CC(C)CC1=CC=C(C=C1)C(C)C(=O)O", inchikey: "HEFNNWSXXWATRW-UHFFFAOYSA-N" }] },
  { id: "amoxyclav-625", brandName: "Amoxyclav 625", aliases: ["amoxyclav", "amoxyclav625", "amoxicillin clavulanate"], manufacturer: "Abbott Healthcare Pvt Ltd", category: "Antibiotic / fixed-dose combination", sourceType: "Local curated prototype dataset", sourceUrls: ["https://pharmeasy.in/online-medicine-order/amoxyclav-625mg-tab-10-s-214164"], salts: [{ salt: "Amoxicillin", synonyms: ["Amoxycillin"], strength: "500 mg", amountPerUnitMg: 500, smiles: "CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=C(C=C3)O)N)C(=O)O)C", inchikey: "LSQZJLSUYDQPKJ-MBNYWOFBSA-N" }, { salt: "Clavulanic Acid", synonyms: ["Clavulanate"], strength: "125 mg", amountPerUnitMg: 125, smiles: "C1C2N(C1=O)C(C(O2)=CCO)C(=O)O", inchikey: "HNYUZQJHSCJIDK-UHFFFAOYSA-N" }] },
  { id: "azee-500", brandName: "Azee 500", aliases: ["azee", "azee 500", "azithromycin 500"], manufacturer: "Cipla Ltd", category: "Macrolide antibiotic", sourceType: "Local curated prototype dataset", sourceUrls: ["https://www.apollopharmacy.in/medicine/azee-500mg-tablet"], salts: [{ salt: "Azithromycin", synonyms: ["Azithromycin dihydrate"], strength: "500 mg", amountPerUnitMg: 500, smiles: "CCC1C(C(C(C(C(O1)C)N(C)C)O)C)OC2C(C(C(C(O2)C)O)OC)N(C)C", inchikey: "MQTOSJVFKKJCRP-UHFFFAOYSA-N" }] },
  { id: "allercet-l", brandName: "Allercet-L", aliases: ["allercet l", "allercet-l", "levocetirizine 5", "levocetirizine"], manufacturer: "Micro Labs Ltd", category: "Antihistamine", region: "Karnataka", sourceType: "Local curated prototype dataset", sourceUrls: ["https://www.1mg.com/drugs/allercet-l-tablet-15414"], salts: [{ salt: "Levocetirizine", synonyms: ["Levocetirizine dihydrochloride"], strength: "5 mg", amountPerUnitMg: 5, smiles: "C1CN(CCN1CCOCC(=O)O)C(C2=CC=CC=C2)C3=CC=C(C=C3)Cl.Cl.Cl", inchikey: "PGLIUCLTXOYQMV-GHVWMZMZSA-N" }] },
  { id: "omez-20", brandName: "Omez 20", aliases: ["omez", "omez 20", "omeprazole 20"], manufacturer: "Dr Reddy's Laboratories Ltd", category: "Proton-pump inhibitor", region: "Telangana", sourceType: "Local curated prototype dataset", sourceUrls: ["https://pharmeasy.in/online-medicine-order/omez-20-cap-20-s-173904"], salts: [{ salt: "Omeprazole", synonyms: ["Omeprazole magnesium"], strength: "20 mg", amountPerUnitMg: 20, smiles: "CC1=CN=C(C(=C1OC)C)CS(=O)C2=NC3=C(N2)C=C(C=C3)OC", inchikey: "SUBDBMMJDZJVOS-UHFFFAOYSA-N" }] },
  { id: "toprazol-d", brandName: "Toprazol-D", aliases: ["toprazol d", "toprazol-d", "pantoprazole domperidone"], manufacturer: "Karnataka Antibiotics & Pharmaceuticals Ltd", category: "Proton-pump inhibitor / prokinetic fixed-dose combination", region: "Karnataka", sourceType: "Local curated prototype dataset", sourceUrls: ["https://www.kaplindia.com/toprazol-d/"], salts: [{ salt: "Pantoprazole", synonyms: ["Pantoprazole sodium"], strength: "40 mg", amountPerUnitMg: 40, smiles: "COC1=NC=NC2=C1C(=NN2)S(=O)CC3=CC=C(C=C3)OC", inchikey: "IQPSEEYGBUAQFF-UHFFFAOYSA-N" }, { salt: "Domperidone", synonyms: ["Domperidone maleate"], strength: "30 mg", amountPerUnitMg: 30, smiles: "C1CN(CCC1N2C3=C(C=C(C=C3)Cl)NC2=O)CCCN4C5=CC=CC=C5NC4=O", inchikey: "FGXWKSZFVQUSTL-UHFFFAOYSA-N" }] },
  { id: "medomol-500", brandName: "Medomol 500", aliases: ["medomol", "medomol 500", "medopharm paracetamol"], manufacturer: "Medopharm Pvt Ltd", category: "Analgesic / antipyretic", region: "Tamil Nadu", sourceType: "Local curated prototype dataset", sourceUrls: ["https://www.medopharm.com/radiant/medomol-paracetamol-500mg-tablets/"], salts: [{ salt: "Paracetamol", synonyms: ["Acetaminophen"], strength: "500 mg", amountPerUnitMg: 500, smiles: "CC(=O)NC1=CC=C(O)C=C1", inchikey: "RZVAJINKPMORJF-UHFFFAOYSA-N" }] },
  { id: "ksdp-azithromycin-500", brandName: "KSDP Azithromycin 500", aliases: ["ksdp azithromycin", "ksdp azithro 500", "kerala state drugs azithromycin"], manufacturer: "Kerala State Drugs & Pharmaceuticals Ltd", category: "Macrolide antibiotic", region: "Kerala", sourceType: "Local curated prototype dataset", sourceUrls: ["https://ksdp.co.in/portfolio/tablets/"], salts: [{ salt: "Azithromycin", synonyms: ["Azithromycin dihydrate"], strength: "500 mg", amountPerUnitMg: 500, smiles: "CCC1C(C(C(C(C(O1)C)N(C)C)O)C)OC2C(C(C(C(O2)C)O)OC)N(C)C", inchikey: "MQTOSJVFKKJCRP-UHFFFAOYSA-N" }] },
];

export function normalizeBrandQuery(query: string) {
  const normalized = query.trim().toLowerCase().replace(/[^a-z0-9]/g, "");
  return brands.filter((brand) => [brand.brandName, ...brand.aliases].some((value) => value.toLowerCase().replace(/[^a-z0-9]/g, "").includes(normalized)));
}

export function getBrandsByIds(ids: string[]) {
  return brands.filter((brand) => ids.includes(brand.id));
}
