import type { Brand } from "./medicines";

export type Quantity = { brandId: string; unitsPerDay: number };
export type Finding = { id: string; severity: "CRITICAL" | "HIGH" | "MODERATE" | "LOW"; title: string; mechanism: string; clinicalAdvice: string; affectedSalts: string[]; sourceType: "Curated clinical rule" | "Dose threshold rule" | "Predictive heuristic"; evidence: string; predictiveScore?: number; confidence?: "Low" | "Medium" | "High" };
export type MatrixCell = { row: string; column: string; severity: Finding["severity"] | "NONE"; sourceType?: Finding["sourceType"] };

const pairRules = [
  { ids: ["Tamoxifen", "Diphenhydramine"], severity: "CRITICAL" as const, title: "Potential reduction in tamoxifen activation", mechanism: "Diphenhydramine is represented in this prototype as a CYP2D6-inhibiting antihistamine; CYP2D6 activity is relevant to formation of active tamoxifen metabolites.", clinicalAdvice: "Discuss a non-interacting alternative with the treating oncology team or pharmacist before use.", evidence: "Curated prototype rule mapped to the resolved salts." },
  { ids: ["Warfarin", "Ibuprofen"], severity: "CRITICAL" as const, title: "Elevated bleeding hazard", mechanism: "Warfarin reduces clotting-factor activity while ibuprofen can impair platelet function and irritate the gastrointestinal mucosa.", clinicalAdvice: "Do not combine without prescriber guidance. Seek urgent care for black stools, vomiting blood, fainting, or uncontrolled bleeding.", evidence: "Curated prototype rule mapped to the resolved salts." },
  { ids: ["Methotrexate", "Amoxicillin"], severity: "CRITICAL" as const, title: "Potential methotrexate accumulation", mechanism: "Penicillin-class therapy may reduce renal tubular secretion of methotrexate, increasing exposure in some clinical settings.", clinicalAdvice: "Contact the prescriber promptly; monitoring and an alternative antibiotic may be required.", evidence: "Curated prototype rule mapped to the resolved salts." },
  { ids: ["Warfarin", "Azithromycin"], severity: "HIGH" as const, title: "Anticoagulation may become unstable", mechanism: "Macrolide-class antibiotics can alter warfarin response and may increase bleeding risk.", clinicalAdvice: "Confirm the plan with the prescriber and ask whether INR monitoring is needed.", evidence: "Curated prototype rule mapped to the resolved salts." },
  { ids: ["Azithromycin", "Tamoxifen"], severity: "HIGH" as const, title: "Potential additive QT-prolongation risk", mechanism: "Both resolved therapies are flagged by this prototype for possible cardiac repolarization risk in susceptible patients.", clinicalAdvice: "Clinician review is important, especially with heart disease, low potassium, fainting, or other QT-prolonging medicines.", evidence: "Curated prototype rule mapped to the resolved salts." },
  { ids: ["Ibuprofen", "Methotrexate"], severity: "HIGH" as const, title: "Potential renal-clearance competition", mechanism: "NSAID exposure may reduce renal clearance of methotrexate in some patients and may add renal stress.", clinicalAdvice: "Ask the prescriber before combining; do not self-adjust either medicine.", evidence: "Curated prototype rule mapped to the resolved salts." },
];
const severityRank = { NONE: 0, LOW: 1, MODERATE: 2, HIGH: 3, CRITICAL: 4 } as const;

/** Deterministic fallback: hashes SMILES character windows into a reproducible 1024-bit descriptor. It is fingerprint-style, not a validated Morgan/RDKit model. */
export function fingerprint1024(smiles: string) { const bits = new Uint8Array(1024); const source = smiles.replace(/\s/g, ""); for (let i = 0; i < source.length - 1; i++) { let hash = 2166136261; for (const char of source.slice(i, i + 3)) hash = Math.imul(hash ^ char.charCodeAt(0), 16777619); bits[Math.abs(hash) % 1024] = 1; } return bits; }
export function fingerprintSimilarity(a: string, b: string) { const left = fingerprint1024(a), right = fingerprint1024(b); let overlap = 0, union = 0; for (let i = 0; i < 1024; i++) { if (left[i] || right[i]) union++; if (left[i] && right[i]) overlap++; } return union ? overlap / union : 0; }

export function analyzeSafety(brands: Brand[], quantities: Quantity[]): { findings: Finding[]; totals: Record<string, number>; matrix: MatrixCell[]; summary: { critical: number; high: number; moderate: number; low: number } } {
  const findings: Finding[] = []; const salts = brands.flatMap((brand) => brand.salts.map((salt) => salt.salt)); const matrix: MatrixCell[] = [];
  for (let i = 0; i < salts.length; i++) for (let j = i + 1; j < salts.length; j++) {
    const match = pairRules.find((rule) => rule.ids.includes(salts[i]) && rule.ids.includes(salts[j]));
    if (match) findings.push({ id: `${match.ids.join("-")}-${i}-${j}`, severity: match.severity, title: match.title, mechanism: match.mechanism, clinicalAdvice: match.clinicalAdvice, affectedSalts: match.ids, sourceType: "Curated clinical rule", evidence: match.evidence });
    const severity = match?.severity || "LOW"; matrix.push({ row: salts[i], column: salts[j], severity, sourceType: match ? "Curated clinical rule" : "Predictive heuristic" });
    if (!match) matrix.push({ row: salts[j], column: salts[i], severity, sourceType: match ? "Curated clinical rule" : "Predictive heuristic" });
  }
  const totals: Record<string, number> = {}; for (const quantity of quantities) { const brand = brands.find((candidate) => candidate.id === quantity.brandId); if (!brand) continue; for (const salt of brand.salts) if (salt.amountPerUnitMg) totals[salt.salt] = (totals[salt.salt] || 0) + salt.amountPerUnitMg * quantity.unitsPerDay; }
  if ((totals.Paracetamol || 0) > 4000) findings.push({ id: "paracetamol-overlap", severity: "CRITICAL", title: "Paracetamol total exceeds prototype daily threshold", mechanism: `The entered regimen totals ${totals.Paracetamol} mg/day across selected brands.`, clinicalAdvice: "Stop and confirm the regimen with a clinician or pharmacist before taking another dose. Seek urgent advice if an overdose may have occurred.", affectedSalts: ["Paracetamol"], sourceType: "Dose threshold rule", evidence: "Prototype threshold: 4,000 mg/day; individual limits vary by patient and product label." });
  else if ((totals.Paracetamol || 0) > 3000) findings.push({ id: "paracetamol-caution", severity: "MODERATE", title: "High cumulative paracetamol exposure", mechanism: `The entered regimen totals ${totals.Paracetamol} mg/day across selected brands.`, clinicalAdvice: "Review all combination products with a pharmacist; lower limits may apply based on liver health, alcohol use, age, or other factors.", affectedSalts: ["Paracetamol"], sourceType: "Dose threshold rule", evidence: "Prototype caution threshold: above 3,000 mg/day." });
  if (brands.length >= 2 && findings.length === 0) {
    const pairs = brands.flatMap((first) => first.salts.flatMap((a) => brands.filter((second) => second.id !== first.id).flatMap((second) => second.salts.map((b) => fingerprintSimilarity(a.smiles, b.smiles))))); const score = Math.round((Math.max(...pairs, 0) * 0.7 + Math.min(1, salts.length / 8) * 0.3) * 100);
    const confidence = score >= 70 ? "High" : score >= 40 ? "Medium" : "Low";
    findings.push({ id: "predictive-screen", severity: score >= 70 ? "MODERATE" : "LOW", title: "Fallback predictive screen for unmapped pairs", mechanism: `The local descriptor comparison produced a ${score}% structural-overlap signal using 1024-bit SMILES window fingerprints.`, clinicalAdvice: "This is not evidence of safety or a clinical prediction. Confirm the complete list with a pharmacist, especially for chronic disease or pregnancy.", affectedSalts: salts.slice(0, 6), sourceType: "Predictive heuristic", evidence: "Transparent deterministic prototype; not RDKit/XGBoost and not validated for patient care.", predictiveScore: score, confidence });
  }
  findings.sort((a, b) => severityRank[b.severity] - severityRank[a.severity]); const summary = { critical: findings.filter((f) => f.severity === "CRITICAL").length, high: findings.filter((f) => f.severity === "HIGH").length, moderate: findings.filter((f) => f.severity === "MODERATE").length, low: findings.filter((f) => f.severity === "LOW").length }; return { findings, totals, matrix, summary };
}

export function buildEvidenceExplanation(findings: Finding[], selectedNames: string[]) { if (!findings.length) return "No safety findings are currently displayed. Add medicines and run a check to generate an evidence-limited explanation."; const lead = findings[0]; return `Based only on the ${selectedNames.join(", ")} resolved in this check, the most important displayed finding is “${lead.title}.” It is labeled ${lead.sourceType.toLowerCase()} and involves ${lead.affectedSalts.join(" + ")}. The mechanism shown is: ${lead.mechanism} Follow the on-screen clinical guidance and confirm the complete regimen with a pharmacist or clinician.`; }
